[package]
name = "file2link"
version = "0.1.0"
edition = "2021"

[dependencies]
teloxide = { version = "0.12", features = ["macros"] }
log = "0.4"
pretty_env_logger = "0.5.0"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
dotenv = "0.15"
reqwest = "0.12.5"
uuid = "1.9.1"
http = "1.1.0"
serde_json = "1.0.118"
axum = "0.7.5"
mime_guess = "2.0.4"
serde = { version = "1.0.203", features = ["derive"] }