version: '3.7'

services:
  app:
    build: .
    depends_on:
      - nginx
    restart: unless-stopped
    ports:
      - "8080:8081"
    volumes:
      - ./files:/files
    env_file:
      - .env
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    restart: unless-stopped
    volumes:
      - ./telegram-bot-api-data:/var/lib/telegram-bot-api
    env_file:
      - .env
  nginx:
    image: nginx:1.19-alpine
    restart: unless-stopped
    depends_on:
      - telegram-bot-api
    volumes:
      - ./telegram-bot-api-data:/var/lib/telegram-bot-api
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "8088:80"
