version: '3.7'

services:
  app:
    env_file:
      - .env
    build: .
    ports:
      - "8080:8080"
#    command: sleep infinity
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    environment:
      TELEGRAM_API_ID: "1234567"
      TELEGRAM_API_HASH: "abcdefghijklmnopqrstuvwxyz0123456789"
    volumes:
      - telegram-bot-api-data:/var/lib/telegram-bot-api
    ports:
      - "8081:8081"

volumes:
  telegram-bot-api-data:
