version: '3.7'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./files:/files
  telegram-bot-api:
    image: aiogram/telegram-bot-api:latest
    restart: always
    env_file:
      - .env
  nginx:
    image: nginx:1.19-alpine
    restart: always
    depends_on:
      - telegram-bot-api
    volumes:
      - ./telegram-bot-api-data:/var/lib/telegram-bot-api
      - ./nginx:/etc/nginx/conf.d/
    ports:
      - "8088:80"

