[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
log = "0.4"
pretty_env_logger = "0.5.0"
once_cell = "1.19.0"
tokio = { version = "1.38.0", features = ["full"] }
serde = { version = "1.0.203", features = ["derive"] }
libc = "0.2.155"
serde_json = "1.0.124"
