name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: cargo build --release

      - name: Upload Binaries
        uses: actions/upload-artifact@v3
        with:
          name: File2Link binaries
          path: |
            target/release/file2link
            target/release/f2l-cli

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Download Binaries
        uses: actions/download-artifact@v3
        with:
          name: File2Link binaries
          path: target/release

      - name: Run tests
        run: cargo test --release
